### ISSUE TITLE
React-Intl FormattedMessage with values is not working in Edge browser

### ISSUE THREAD

**Issue by nevendyulgerov** [formatjs/formatjs#2836] opened 2021-04-17 13:25 UTC
## Which package?
[React-Intl](https://www.npmjs.com/package/react-intl)

## Describe the bug
`FormattedMessage` available from the `react-intl` package does not work with `values` under Edge browser.

## To Reproduce
In React context, define the following app:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import { IntlProvider, FormattedMessage } from 'react-intl';

ReactDOM.render(
  <IntlProvider locale="en">
    <FormattedMessage
      id="termsOfService"
      defaultMessage="© Terms of Service. {year}. All Rights Reserved"
      values={{ year: new Date().getFullYear() }}
    />
  </IntlProvider>,
  document.getElementById('react-app')
);
```

### Reproducible Steps/Repo

1. Execute the above code in React context
2. Open the app in Edge
3. Notice that `{year}` remains and the passed value in `values` is not applied
4. See error:

```
[object Error]: {code: "FORMAT_ERROR", description: "[@formatjs/intl Error FORMAT_ERROR] Error formatting default message for: "termsOfService", rendering default message verbatim Locale: en MessageID: termsOfService Default Message: © Terms of Service. {year}. All Rights Reserved Description: undefined MALFORMED_ARGUMENT SyntaxError: MALFORMED_ARGUMENT at parse (http://localhost:8080/dist/main.bundle.js:53066:9) at IntlMessageFormat (http://localhost:8080/dist/main.bundle.js:52929:13) at Anonymous function (http://localhost:8080/dist/main.bundle.js:52688:13) at variadic (http://localhost:8080/dist/main.bundle.js:55053:5) at formatMessage (http://localhost:8080/dist/main.bundle.js:55563:17) at formatMessage (http://localhost:8080/dist/main.bundle.js:56105:5) at FormattedMessage (http://localhost:8080/dist/main.bundle.js:56377:5) at renderWithHooks (http://localhost:8080/dist/main.bundle.js:34098:3) at mountIndeterminateComponent (http://localhost:8080/dist/main.bundle.js:36924:5) at beginWork (http://localhost:8080/dist/main.bundle.js:38162:9)", descriptor: Object, message: "[@formatjs/intl Error FORMAT_ERROR] Error formatting default message for: "termsOfService", rendering default message verbatim Locale: en MessageID: termsOfService Default Message: © Terms of Service. {year}. All Rights Reserved Description: undefined MALFORMED_ARGUMENT SyntaxError: MALFORMED_ARGUMENT at parse (http://localhost:8080/dist/main.bundle.js:53066:9) at IntlMessageFormat (http://localhost:8080/dist/main.bundle.js:52929:13) at Anonymous function (http://localhost:8080/dist/main.bundle.js:52688:13) at variadic (http://localhost:8080/dist/main.bundle.js:55053:5) at formatMessage (http://localhost:8080/dist/main.bundle.js:55563:17) at formatMessage (http://localhost:8080/dist/main.bundle.js:56105:5) at FormattedMessage (http://localhost:8080/dist/main.bundle.js:56377:5) at renderWithHooks (http://localhost:8080/dist/main.bundle.js:34098:3) at mountIndeterminateComponent (http://localhost:8080/dist/main.bundle.js:36924:5) at beginWork (http://localhost:8080/dist/main.bundle.js:38162:9)", stack: "Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting default message for: "termsOfService", rendering default message verbatim Locale: en MessageID: termsOfService Default Message: © Terms of Service. {year}. All Rights Reserved Description: undefined MALFORMED_ARGUMENT SyntaxError: MALFORMED_ARGUMENT at parse (http://localhost:8080/dist/main.bundle.js:53066:9) at IntlMessageFormat (http://localhost:8080/dist/main.bundle.js:52929:13) at Anonymous function (http://localhost:8080/dist/main.bundle.js:52688:13) at variadic (http://localhost:8080/dist/main.bundle.js:55053:5) at formatMessage (http://localhost:8080/dist/main.bundle.js:55563:17) at formatMessage (http://localhost:8080/dist/main.bundle.js:56105:5) at FormattedMessage (http://localhost:8080/dist/main.bundle.js:56377:5) at renderWithHooks (http://localhost:8080/dist/main.bundle.js:34098:3) at mountIndeterminateComponent (http://localhost:8080/dist/main.bundle.js:36924:5) at beginWork (http://localhost:8080/dist/main.bundle.js:38162:9) at IntlError (http://localhost:8080/dist/main.bundle.js:55429:9) at MessageFormatError (http://localhost:8080/dist/main.bundle.js:55466:9) at formatMessage (http://localhost:8080/dist/main.bundle.js:55567:17) at formatMessage (http://localhost:8080/dist/main.bundle.js:56105:5) at FormattedMessage (http://localhost:8080/dist/main.bundle.js:56377:5) at renderWithHooks (http://localhost:8080/dist/main.bundle.js:34098:3) at mountIndeterminateComponent (http://localhost:8080/dist/main.bundle.js:36924:5) at beginWork (http://localhost:8080/dist/main.bundle.js:38162:9) at beginWork$1 (http://localhost:8080/dist/main.bundle.js:43048:7) at performUnitOfWork (http://localhost:8080/dist/main.bundle.js:41887:5)"}
```

## Expected behavior
Instead of `{year}`, that part of the message should be replaced with the passed value in `values`. In this case, this should be `2021`.

## Screenshots
![react-intl-format-message-error](https://user-images.githubusercontent.com/6005179/115114638-11a87f00-9f99-11eb-87f3-fec42787e038.PNG)

## Desktop:
- OS: Windows 10
- Edge
- 18

**Comment by longlho** [comment] 2021-04-17 13:29
Can you make a codesandbox?

**Comment by nevendyulgerov** [comment] 2021-04-17 13:46
I tried but unfortunately codesandbox does not work in Edge.

**Comment by nevendyulgerov** [comment] 2021-04-18 06:17
It appears that I was not using the latest Edge version. I just updated it and the issue is no longer reproducible, thanks!

**Comment by imguolao** [comment] 2021-04-20 12:30
I got the same error !!!

```js
code: "FORMAT_ERROR"
description: "[@formatjs/intl Error FORMAT_ERROR] Error formatting message: "app.home.select", using id as fallback. 
Locale: en-US MessageID: app.home.select 
Default Message: undefined 
Description: undefined 
MALFORMED_ARGUMENT SyntaxError: MALFORMED_ARGUMENT at parse (eval code:14981:7) 
at IntlMessageFormat (eval code:15553:7) 
at Anonymous function (eval code:15852:7) at variadic (eval code:15033:5) at formatMessage
```

browser version:
- Windows 10
- Edge 18

![image](https://user-images.githubusercontent.com/25502024/115396112-3ad64300-a217-11eb-9ccd-d8a81a49a37d.png)

**Comment by imguolao** [comment] 2021-04-20 12:46
I need to be compatible the old browser, so i can’t  solve it by upgrading the browser.

What should i do?

**Comment by longlho** [comment] 2021-04-20 13:03
What's the string that gave you that error?

**Comment by imguolao** [comment] 2021-04-21 01:42
> What's the string that gave you that error?

below code is a vue demo i wrote:

```html
<template>
  <div class="hello">
    <div>{{ translateSelect(0) }}</div>
    <div>{{ translateSelect(1) }}</div>
    <div>{{ translateSelect(2) }}</div>
  </div>
</template>

<script>
import { createIntl, createIntlCache } from '@formatjs/intl'

const intl = createIntl({
  locale: 'en-US',
  timeZone: 'Asia/Shanghai',
  messages: {
    'app.home.title': 'Hello, {name}!',
    'app.home.price': '{price, number, CNY}',
    'app.home.select': 'select {count, plural, one {one message} other {# messages}}.',
  },
}, createIntlCache())

export default {
  name: 'HelloWorld',
  props: {
    msg: String
  },
  methods: {
    translateSelect (count) {
      return intl.formatMessage({id: 'app.home.select'}, { count })
    }
  }
}
</script>
```

The screenshot is the display result of chrome 89 and dege 18：

![edge_error](https://user-images.githubusercontent.com/25502024/115484636-b2db5200-a285-11eb-80ec-607a881cd5f5.PNG)

**Comment by imguolao** [comment] 2021-04-21 01:45
> What's the string that gave you that error?

console display these error in edge 18:

![egde_console_error](https://user-images.githubusercontent.com/25502024/115484918-3d23b600-a286-11eb-816c-3aa8c6fc15b3.PNG)

**Comment by imguolao** [comment] 2021-04-21 01:50
But this demo can work under ie11，surprising.

**Comment by imguolao** [comment] 2021-04-21 02:14
I think I found the reason.

The following code is on line 210 of formatjs/packages/icu-messageformat-parser/parser.ts

```ts
let matchIdentifierAtIndex: (s: string, index: number) => string
if (REGEX_SUPPORTS_U_AND_Y) {
  // Native
  const IDENTIFIER_PREFIX_RE = RE(
    '([^\\p{White_Space}\\p{Pattern_Syntax}]*)',
    'yu'
  )
  matchIdentifierAtIndex = function matchIdentifierAtIndex(s, index) {
    IDENTIFIER_PREFIX_RE.lastIndex = index
    const match = IDENTIFIER_PREFIX_RE.exec(s)!
    return match[1] ?? ''
  }
} else {
  // IE11
  matchIdentifierAtIndex = function matchIdentifierAtIndex(s, index) {
    let match: number[] = []
    while (true) {
      const c = codePointAt(s, index)
      if (c === undefined || _isWhiteSpace(c) || _isPatternSyntax(c)) {
        break
      }
      match.push(c)
      index += c >= 0x10000 ? 2 : 1
    }
    return fromCodePoint(...match)
  }
}
```

When I comment out the `Native` code above and use the code of the `IE11` part, it works fine under edge18.

**Comment by longlho** [comment] 2021-04-21 04:09
dupe of #2822

**Closed as completed** 2021-04-21 04:09 UTC
Labels: bug
