### ISSUE TITLE
[intl-datetimeformat] DateTimeFormat output not as standard

### ISSUE THREAD

**Issue by chenqy930** [formatjs/formatjs#1915] opened 2020-08-03 13:13 UTC
**Which package?**
@formatjs/intl-datetimeformat 2.3.0

**Describe the bug**
Using Intl.DateTimeFormat().format(), the output is wrong in some cases.

**To Reproduce**
    In node enviroment, test the following case, and the expected output and actual output are as commented:
```   
    require('@formatjs/intl-datetimeformat/polyfill');
    require('@formatjs/intl-datetimeformat/locale-data/en.js');

    // case 1
    // expected output: 9:05PM (time right now)
    // actual output: 1:10 PM (about 8 hours behind)
    var date_2 = new Date();
    var options_2 = { hour: 'numeric', minute: 'numeric' };
    console.log(new Intl.DateTimeFormat('en', options_2).format(date_2));

    // case 2
    // expected output: August
    // actual output: week  of August
    var date_4 = new Date();  
    var options_4 = { month:'long' };  
    console.log(new Intl.DateTimeFormat('en', options_4).format(date_4));
```

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Linux 16.04
- using Nodejs v10.16.3

**Comment by longlho** [comment] 2020-08-04 14:49
Thanks for reporting! We'll take a look asap.

**Comment by longlho** [comment] 2020-08-05 00:40
For case 1, you need to specify your `timeZone` and add IANA data. We have no way of detecting what the local `timeZone` is since that info is not exposed from the runtime.

We'll take a look at case 2

**Comment by chenqy930** [comment] 2020-08-05 13:27
@longlho hi, Thanks for your help. I tried the solution for case 1, but it dosen't seem working. Here's how I do as you recommanded.
```
require('@formatjs/intl-datetimeformat/polyfill');
require('@formatjs/intl-datetimeformat/locale-data/zh.js');
require('@formatjs/intl-datetimeformat/add-all-tz.js');  // the path here is a little bit different from that in document of formatjs.io, which goes "import '@formatjs/intl-datetimeformat/dist/add-all-tz.js';"

 var date_2 = new Date();
// specify timeZone
var options_2 = { hour: 'numeric', minute: 'numeric', timeZone: 'Asia/Shanghai' };
console.log(new Intl.DateTimeFormat('zh-cn', options_2).format(date_2));  // output 13:14
// not specify timeZone
var options_21 = { hour: 'numeric', minute: 'numeric' };
console.log(new Intl.DateTimeFormat('zh-cn', options_21).format(date_2));  // output: 13:14
```

Whether or not specify timeZone, the time output is always 8 hours behind.

**Comment by longlho** [comment] 2020-08-06 16:49
OK we'll take a look asap

**Comment by longlho** [comment] 2020-08-11 04:41
@chenqy930 I've pushed a fix for case 2 so if u can check out latest on `main` that'd be great.
For case 1, can u clarify the current timezone for your node process?
I added a test and it seems to behave correctly https://github.com/formatjs/formatjs/blob/main/packages/intl-datetimeformat/tests/index.test.ts#L41

**Comment by chenqy930** [comment] 2020-08-12 01:29
@longlho Thanks for your effor~ I've tried @formatjs/intl-datetimeformat v2.3.1, the latest version, and case 2 was fixed right.
And for case1, I checked my current timezone using process.env.TZ, it's undefined.

**Comment by longlho** [comment] 2020-08-12 02:48
@chenqy930 can u put together a repo to reproduce the issue? I haven't been able to

**Comment by chenqy930** [comment] 2020-08-12 02:55
Plus I found another case that output not quite right, it's seems related to locale data.
```
// choose "en" locale, the output is right.
// standard: Wednesday, August 12
// output: Wednesday, August 12
 var date_3_1 = new Date();
 var options_3_1 = { weekday:'long', month: 'long', day: 'numeric' };
 console.log(new Intl.DateTimeFormat('en', options_3_1).format(date_3_1));

// choose "zh-cn" locale, the output is different.
// standard: 8月12日星期三
// output: 8/12星期三
var date_3 = new Date();
var options_3 = { weekday:'long', month: 'long', day: 'numeric' };
console.log(new Intl.DateTimeFormat('zh-cn', options_3).format(date_3));
```

**Comment by longlho** [comment] 2020-08-12 02:57
yeah it's bc there's a bug in how Node 10 resolves locale aliases. Try importing https://formatjs.io/docs/polyfills/intl-getcanonicallocales before importing `@formatjs/intl-numberformat`.

**Comment by chenqy930** [comment] 2020-08-12 02:59
@longlho  Umm how to put together a repo? 
I use npm init, then put those js code in a file, and node xx.js to execute.

**Comment by longlho** [comment] 2020-08-12 03:00
You can just make a new GitHub repo with the code

**Comment by chenqy930** [comment] 2020-08-12 03:08
ok, I will do that later, and try that solution for DateTimeFormat locale difference.

**Comment by chenqy930** [comment] 2020-08-14 14:07
@longlho so sorry for the late reply.
I put my test code together, and you can use npm init, npm install related @foramtjs/intl-xxxx packages, then "node test.js" should be able to reproduce the senarios:
```
require('@formatjs/intl-getcanonicallocales/polyfill');

require('@formatjs/intl-numberformat/polyfill');
require('@formatjs/intl-numberformat/locale-data/ja.js');
require('@formatjs/intl-numberformat/locale-data/zh.js');
require('@formatjs/intl-numberformat/locale-data/en.js');

require('@formatjs/intl-datetimeformat/polyfill');
require('@formatjs/intl-datetimeformat/locale-data/zh.js');
require('@formatjs/intl-datetimeformat/locale-data/en.js');
require('@formatjs/intl-datetimeformat/add-golden-tz.js');


function checkDateTimeFormat()
{
    console.log("==Test name: checkDateTimeFormat");

    var date_2 = new Date();
    var options_2 = { hour: 'numeric', minute: 'numeric' };
    console.log(new Intl.DateTimeFormat('zh-cn', options_2).format(date_2));  // 13:42, expected: "下午10:04"

    var date_2_1 = new Date();
    var options_2_1 = { hour: 'numeric', minute: 'numeric', timeZone:'Asia/Shanghai' }; 
    console.log(new Intl.DateTimeFormat('zh-cn', options_2_1).format(date_2_1));  // 13:42, expected: "下午10:04"
    
    var date_3 = new Date();
    var options_3 = { weekday:'long', month: 'long', day: 'numeric' };
    console.log(new Intl.DateTimeFormat('zh-cn', options_3).format(date_3)); // 8/14星期五, expected: "8月14日星期五"

    var date_3_1 = new Date();
    var options_3_1 = { weekday:'long', month: 'long', day: 'numeric' };
    console.log(new Intl.DateTimeFormat('en', options_3_1).format(date_3_1)); // Friday, August 14, same as expected.

    console.log("node timezone is: " + process.env.TZ); // undefined
}

checkDateTimeFormat();
```
1. options {hour: 'numeric', minute: 'numeric'} : seems still not right, 8 hours behind.
2. options { weekday:'long', month: 'long', day: 'numeric' } : try require ''intl-getcanonicallocales'' before NumberFormat, but it dosen't seem change.

**Closed as completed** 2020-08-15 02:58 UTC
Labels: bug

**Comment by longlho** [comment] 2020-08-15 03:03
`@formatjs/intl-datetimeformat@2.4.3` should have the fix for this. Thanks a lot for reporting!

**Comment by RichardLindhout** [comment] 2020-08-17 18:28
I think I have this problem 

With polyfill
![Schermafbeelding 2020-08-17 om 20 27 26](https://user-images.githubusercontent.com/6492229/90430627-16462c00-e0c8-11ea-8ea2-94f5e16877e1.png)

Without polyfill
![Schermafbeelding 2020-08-17 om 20 27 10](https://user-images.githubusercontent.com/6492229/90430632-180fef80-e0c8-11ea-8415-460c823bf824.png)

**Comment by longlho** [comment] 2020-08-17 18:31
@RichardLindhout looks like u have a timezone issue? Did u set `timeZone`? This polyfill also cannot detect default timezone so you'd have to pass that in explicitly, otherwise it defaults to `UTC`.
Can u provide a repro?

**Comment by RichardLindhout** [comment] 2020-08-17 19:02
Ah you're right I put the timezone in the wrong place, I though it did not work but it does :). Thank you

**Comment by RichardLindhout** [comment] 2020-08-17 19:15
any option to set global timezone?

**Comment by longlho** [comment] 2020-08-17 19:55
There is but it's not public. Can u create a GH issue for it?
