### ISSUE TITLE
Babel plugin docs contain undocumented option

### ISSUE THREAD

**Issue by hoschi** [formatjs/formatjs#1953] opened 2020-08-12 11:36 UTC
https://github.com/formatjs/formatjs/blob/62bf0f9fa5bd9dbe72fe1caacaafb8d03fc5ba30/website/docs/tooling/babel-plugin.md#L35

`messagesDir` seems removed in previous version.

**Comment by longlho** [comment] 2020-08-12 13:22
Dupe of #1952

**Closed as completed** 2020-08-12 13:23 UTC
Labels: bug
