### ISSUE TITLE
react-intl FormattedMessage typing problems

### ISSUE THREAD

**Issue by gpessa** [formatjs/formatjs#3593] opened 2022-05-13 10:48 UTC
## Which package?
react-intl

## Describe the bug
Some issue on typing:

```
  <FormattedMessage
    defaultMessage={`<typography>some text</typography>`}
    values={{ typography: (chunks) => <><Typography>{chunks}</Typography></> }}
/>
```
        
Error:

`Type '(chunks: any) => Element' is not assignable to type 'ReactNode'.ts(2322)`

**Comment by gkopowski** [comment] 2022-05-13 12:32
Same here, this issue is most likely related to updating React and types to version 18.

My package.json:
```
"react": "18.1.0",
"react-dom": "18.1.0",
...
"@types/react": "18.0.9",
"@types/react-dom": "18.0.3",
```

**Comment by gpessa** [comment] 2022-05-13 13:23
> Same here, this issue is most likely related to updating React and types to version 18.
> 
> My package.json:
> 
> ```
> "react": "18.1.0",
> "react-dom": "18.1.0",
> ...
> "@types/react": "18.0.9",
> "@types/react-dom": "18.0.3",
> ```

same same with 17.0.2

**Comment by ghazale-javaheri** [comment] 2022-05-14 07:09
any fix?

**Comment by manly8835** [comment] 2022-05-14 14:46
Same here, this issue is most likely related to updating React and types to version 18.

**Comment by gkopowski** [comment] 2022-05-16 10:19
I think I found a specific change that causes the error:

![image](https://user-images.githubusercontent.com/17780702/168571661-1a65d5c5-7b69-4d6a-b712-8dcfadca7217.png)

file: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210/files#diff-32cfd8cb197872bcba371f5018185d2e75fa540b52cda2dd7d8ac12dcc021299

So what can we do about it?

**Comment by gpessa** [comment] 2022-05-16 11:37
> I think I found a specific change that causes the error:
> 
> ![image](https://user-images.githubusercontent.com/17780702/168571661-1a65d5c5-7b69-4d6a-b712-8dcfadca7217.png)
> 
> file: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210/files#diff-32cfd8cb197872bcba371f5018185d2e75fa540b52cda2dd7d8ac12dcc021299
> 
> So what can we do about it?

I might be wrong but even with 17 i have the same issue

**Comment by leethree** [comment] 2022-05-19 14:31
I think this is caused by having both 17 and 18 of `@types/react` installed at the same time. Not sure what's the best way to resolve this

**Comment by longlho** [comment] 2022-05-19 14:58
we'll release a fix soon

**Comment by longlho** [comment] 2022-05-19 14:58
dupe of #3550

**Closed as completed by longlho** 2022-05-19 14:58 UTC
Labels: bug
