### ISSUE TITLE
Eslint doesn't recognize formatMessage alone

### ISSUE THREAD

**Issue by Fxlr8** [formatjs/formatjs#2371] opened 2020-12-03 13:32 UTC
For example, `enforce-placeholders` rule will work here and warn that `{value}` was not provided:
```ts
const intl = useIntl()
const message = intl.formatMessage({id: 'test', defaultMessage: 'this is test number {value}'})
```
But this one does not work at all:
```ts
const { formatMessage } = useIntl()
const message = formatMessage({id: 'test', defaultMessage: 'this is test number {value}'})
```

**Comment by longlho** [comment] 2020-12-03 14:44
Dupe of #2368. You have to declare with intl.formatMessage

**Closed as completed** 2020-12-03 14:44 UTC
Labels: bug

**Comment by Fxlr8** [comment] 2020-12-03 15:24
Nope, this is not a dupe of that issue. This is related to `eslint-plugin-formatjs` and that one is about `babel-plugin-react-intl`. This example works perfectly with messages extraction, only linter fails here. This is a completely different issue, but it looks similar. Consider reopening, please.

**Comment by longlho** [comment] 2020-12-03 15:29
It's a dupe because it's the same root cause
