### ISSUE TITLE
Type issue

### ISSUE THREAD

**Issue by KiprasJ** [formatjs/formatjs#2164] opened 2020-09-30 07:51 UTC
**Which package?**
react-intl 5.8.3

**Describe the bug**
Seems that there is an issue with one of the types.
![image](https://user-images.githubusercontent.com/7200930/94657828-b370c300-030a-11eb-9c09-5ea4258a3bed.png)

**To Reproduce**
Run translations on react-intl 5.8.3

**Expected behavior**
Should work as previosuly

- OS: Ubuntu
- Browser Chrome
- Version latest

**Comment by longlho** [comment] 2020-09-30 07:54
Dupe of #2128

**Closed as completed by longlho** 2020-09-30 07:54 UTC
Labels: bug
