### ISSUE TITLE
Intl.DateTimeFormat.formatRange polyfill returns formatted string with redundant date

### ISSUE THREAD

**Issue by kumikumi** [formatjs/formatjs#2962] opened 2021-06-08 11:38 UTC
## Which package?
intl-datetimeformat

## Describe the bug
Formatting certain date ranges whose start and end times take place in the same date, results in the date being printed for both start and end times.

## To Reproduce
Viewing the following sandbox on Firefox (tried with version 88) shows `Jun 8, 2021, 11:00 AM – Jun 8, 2021, 5:00 PM`. On Google Chrome (not polyfilled), "Jun 8, 2021" is only present once in the result.

### Codesandbox URL
https://codesandbox.io/s/datetimeformat-formatting-nzeje

## Expected behavior
Date part only printed once. For example: `Jun 8, 2021, 11:00 AM – 5:00 PM`

**Comment by longlho** [comment] 2021-06-08 20:35
dupe of #2915

**Closed as completed by longlho** 2021-06-08 20:35 UTC
Labels: bug
