### ISSUE TITLE
Need an opt-out option for the XML tag feature

### ISSUE THREAD

**Issue by mstarets** [formatjs/formatjs#1693] opened 2020-05-28 15:26 UTC
Package: intl-messageformat-parser

Problem description:
The parser violates ICU 4.8 spec by requiring that < and > characters be escaped when they are used in regular message text. Since we are not interested in using the XML tag feature or HTML formatting support, we would like to be able to opt out. 

Proposed solution:
1. Expose 'treatTagsAsText' parser option (exact name TBD)
2. Modify parser.pegjs grammar file to check the option when deciding whether < and > characters require quoting:
function treatTagsAsText() {
     return options && options.treatTagsAsText;
 }
...
unquotedString = $(x:. &{
    return (
        (x !== '<' || treatTagsAsText()) &&
        x !== '{' &&
        !(isInPluralOption() && x === '#') &&
        !(isNestedMessageText() && x === '}') &&
        !(isNestedMessageText() && x === '>' && !treatTagsAsText())
    );
} / '\n')

I'd be happy to submit a pull request if people think that this request is reasonable.

**Comment by longlho** [comment] 2020-05-28 18:18
You can pin `intl-messageformat-parser` to the `v7`. Dupe of #1648

**Closed as completed by longlho** 2020-05-28 18:18 UTC
Labels: enhancement

**Comment by mstarets** [comment] 2020-05-28 20:19
I just wanted to point out that this issue is different from 1648. I am not proposing to reverse the change you made in 8.0. I am asking to add an opt-out flag that would allow us to not require escaping for < and >. All of your existing customers won't be affected at all. The code changes are minimal, and should be easy to maintain.

Pining to an old version is not an option for us. We would like to get your fixes/updates without having to fork and merge.

**Comment by longlho** [comment] 2020-05-28 20:21
What's your use case actually? Do you use any of the top level libs like `intl-messageformat` or `react-intl`?

**Comment by mstarets** [comment] 2020-05-28 20:49
Hey Long, we have our own component framework, and are not using React and react-intl. We are switching our translated message format to ICU 4.8, and decided to use your library (because we liked it a lot!) in two different areas:
1) Build-time transformation of message patterns into formatter functions (along with TypeScript definitions for them) that take message arguments and return fully formatted messages. Here we use only intl-messageformat-parser.
2) Our browser-based designer application is using intl-messageformat (after being being processed with rollup) on the client to format messages shown in the preview pane.
One of our internationalization engineers noticed that the parser is throwing errors for messages like "please enter a number > 5", while ICU does not specify that these characters require escaping with an apostrophe. We figured that the brackets are used to support call-outs to custom formatters to implement message formatting. We have no such requirements though.
For us and apparently for the filer of 1648, it would be super convenient to be able to opt out of  < and > being treated specially and loose the ability to use custom formatter functions. 

I figured that adding an option for the parser to treat < and > as plain text literals would be safe, and that the changes to the pegjs grammar would be very minimal. There would also be no impact on the intl-message-format at all because an AST node with type 8 (tag) would never be generated. 

Thanks,
Max

**Comment by longlho** [comment] 2020-05-28 21:23
Cool thanks a lot for the explanation. We’ll take a look as soon as we can.

**Comment by mstarets** [comment] 2020-06-01 21:43
Would it help if I created a pull request? I's be happy to create a branch with the grammar change, the opt-in flag and a test.

**Comment by longlho** [comment] 2020-06-01 22:16
Yup PR’s always welcome!
