### ISSUE TITLE
Rich Text Formatting: key attribute is not applied when a tag resolves to <li>

### ISSUE THREAD

**Issue by abhayvatoo** [formatjs/formatjs#1672] opened 2020-05-08 20:04 UTC
**Which package?**
react-intl

**Describe the bug**
console warning: `Each child in a list should have a unique "key" prop.` is generated even if a `key` is supplied to `<li>` tag in the `values` prop for `<FormattedMessage>` or `formatMessage`

For example,

for the message described below:
```
const messages = defineMessages({
  greet: {
    id: "welcome",
    defaultMessage:
      "<p>Hi <b>{name}</b></p> <ul> <li>item1</li> <li>item2</li> </ul>"
  }
});
```

and using 
```
intl.formatMessage(messages.greet, {
        name,
        b: (...str) => <b>{str}</b>,
        p: (...str) => <p>{str}</p>,
        ul: (...str) => <ul>{str}</ul>,
        li: (...str) => <li key={str}>{str}</li>
      })
```
A warning `Each child in a list should have a unique "key" prop.` is generated even when we are passing a key i.e. `li: (...str) => <li key={str}>{str}</li>`

**To Reproduce**
https://codesandbox.io/s/key-error-cximr?file=/src/index.js

**Expected behavior**
By supplying a key's value, it should not trigger key error `Each child in a list should have a unique "key" prop.`

**Comment by longlho** [comment] 2020-05-21 03:37
dupe of #1623

**Closed as completed by longlho** 2020-05-21 03:37 UTC
Labels: bug
