### ISSUE TITLE
The intl string context variable 'nameVariable' 

### ISSUE THREAD

**Issue by sergeushenecz** [formatjs/formatjs#3266] opened 2021-11-13 14:31 UTC
## Which package?
react-int: 5.21.1

## Describe the bug
I have string  

`title: Test string {number} `

When i call in the code 

intl.formatMessage(title, { number })

if number  not defined yet then i have error 

**The intl string context variable "number" was not provided to the string "Test string {number}"
Error: The intl string context variable "terminalName" was not provided to the string "Test string {number}"**

earlier it is work as excepted without error.

**Comment by longlho** [comment] 2021-11-14 04:05
dupe of #3263

**Closed as completed by longlho** 2021-11-14 04:05 UTC
Labels: bug
