### ISSUE TITLE
[React-intls]: wrap as client component.

### ISSUE THREAD

**Issue by AugustinMauroy** [formatjs/formatjs#4189] opened 2023-09-08 21:47 UTC
Now with react 18 and react server component, if you wan to use i18n in server app you should wrap you i18n:

```tsx
'use client';
import { FormattedMessage } from 'react-intl';
import type { FC, ElementType } from 'react';

type Props = {
	id: string;
	tagName?: ElementType<any>;
	values?: any;
};

const LocalizedMessage: FC<Props> = ({ id, tagName, values }) => (
	<FormattedMessage id={id} tagName={tagName} values={values} />
);

export default LocalizedMessage;
```

## How to solve this problem ?

My idea it's do hard an `'use client'` on top of [index.tsx](https://github.com/formatjs/formatjs/blob/main/packages/react-intl/index.ts)

But I'm no sure if `tsc` compiler will keep it at first line of file

**Comment by longlho** [comment] 2023-09-18 03:14
dupe of #4192

**Closed as completed by longlho** 2023-09-18 03:14 UTC
