### ISSUE TITLE
react-intl TypeScript import error.

### ISSUE THREAD

**Issue by mbugerald** [formatjs/formatjs#2217] opened 2020-10-14 06:59 UTC
**Which package?**
react-intl 

**Describe the bug**
Hi guys, first of all thanks for all the work. I noticed a bug using react-intl with typescript **import type { PrimitiveType, FormatXMLElementFn } from 'intl-messageformat';** breaks because of import error. please can you correct it? I remove the type statement before the {PrimitiveType just after the import statement on line 3, in the latest version. 
**source: react-intl > src > component > message.d.ts**.

**Comment by longlho** [comment] 2020-10-15 01:06
dupe of #2128

**Closed as completed by longlho** 2020-10-15 01:06 UTC
Labels: bug
