### ISSUE TITLE
[react-intl] "TypeError: messages.hasOwnProperty is not a function" after updating patch version "5.4.2" to "5.4.5",

### ISSUE THREAD

**Issue by JustFly1984** [formatjs/formatjs#1914] opened 2020-08-03 12:23 UTC
**Which package?**
[react-intl]

**Describe the bug**
I'm updating react-intl in gatsby.js project, and I'm facing a runtime error on load, and cypress tests failing.

<img width="785" alt="Screenshot 2020-08-03 19 16 04" src="https://user-images.githubusercontent.com/2255993/89181437-eeca6c00-d5bd-11ea-8420-cddbe317fbf4.png">

reverting back to 5.4.2 solves an issue.

**Comment by longlho** [comment] 2020-08-03 15:56
hmm do u have a repro? looks like it's passing in `messages` that's not an object?

**Comment by JustFly1984** [comment] 2020-08-03 16:05
How can that be an object for 5.4.2 and not an object for 5.4.5?

**Comment by JustFly1984** [comment] 2020-08-03 16:08
I do not have reproduction which I can share, but I have reproduced it in 2nd gatsby.js project

**Comment by longlho** [comment] 2020-08-03 16:10
If you `messages` was a result of `Object.create(null)` then it does not have `hasOwnProperty`, but `messages[foo]` would still work. How are you creating that object?

Before in `5.4.2` we did not have that check, the check was added to fix #1885

**Comment by longlho** [comment] 2020-08-03 16:26
this should be fairly easy to fix but understanding what gatby.js is doing would be great 😄

**Comment by JustFly1984** [comment] 2020-08-05 06:32
I do not think this is related to gatsby itself, more like typescript/webpack dynamic imports json

@longlho 
I found the code which dynamically imports messages in our gatsby.js project:

in gatsby-ssr.js - runs only on build, doesn't run in browser
```
export function wrapPageElement({ element, props }) {
  const locale = props.pageContext.locale || 'en'

  intlManager.setMessages(locale, require(`./src/const/intl/${locale}.json`))

  return element
}
```

the code for intlManager class:

```
 function importLocaleData(locale: Locale): Promise<IntlMessages> {
  switch (locale) {
    case 'en': {
      return import('../const/intl/en.json')
    }
    case 'ru': {
      return import('../const/intl/ru.json')
    }
    default: {
      const unknown: never = locale

      throw new Error(`Unexpected locale "${unknown}"`)
    }
  }
}
```

This way we extracting locale files out from main bundle js file to improve performance.
We are calling importLocaleData on init and language switch.

We have typescript config "resolveJsonModule": true, so dynamic imports are working correctly, but I'm not sure how typescript and webpack handle object creation transpilation under the hood, but patch update has regression conflict with dynamic json import.

**Comment by jimisaacs** [comment] 2020-08-06 01:11
I see this error too after an upgrade from `5.3.2` to `5.4.5`. We only use webpack, not gatsby or any other wrapper. One thing that might be related, is that we also upgraded `@formatjs/intl-relativetimeformat` from `6.2.3` to `7.0.0`.

**Comment by jimisaacs** [comment] 2020-08-06 01:19
I can confirm this broke us: https://github.com/formatjs/formatjs/commit/a42cdec44c5cba184832ad9703cf2aa7cf2f1be4#diff-75a85a349ceef1cdc44fd9c2e925c2e6

To provide more info, we do not create a messages object, we dynamically import it using webpack, e.g.
```
const messages = await import('my/local/messages.json');
```
I have a feeling something in the above doesn't come out with a `hasOwnProperty`.

**Comment by jimisaacs** [comment] 2020-08-06 01:23
Looks to be it:
<img width="419" alt="Screen Shot 2020-08-05 at 6 22 23 PM" src="https://user-images.githubusercontent.com/299156/89479857-c58a1700-d748-11ea-873b-4d58ea019a46.png">

**Comment by jimisaacs** [comment] 2020-08-06 01:24
Though interestingly the `messages.default` (e.g. `module.default`) does have a prototype.

**Comment by jimisaacs** [comment] 2020-08-06 01:31
I think the right fix is for me to change to the default module property here as this actually caught my bad behavior.

**Comment by JustFly1984** [comment] 2020-08-06 06:18
@jimisaacs can you please post your fix here?

**Comment by longlho** [comment] 2020-08-06 06:40
I'll put up a fix for this regardless even though it's quite edge. To repro w/o the `import` issue basically you can just do `const messages = Object.create(null);`

**Closed as completed** 2020-08-06 07:00 UTC
Labels: bug

**Comment by drkibitz** [comment] 2020-08-06 14:31
Out of curiosity, what is hasOwnProperty accomplishing here? You can also call `Object.prototype.hasOwnProperty.call(messages, id);`

**Comment by longlho** [comment] 2020-08-06 15:36
@drkibitz see https://github.com/formatjs/formatjs/issues/1885 for more context :)

**Comment by jimisaacs** [comment] 2020-08-06 17:08
@longlho 

+1 on the suggestion of: `Object.prototype.hasOwnProperty.call(messages, id);`

@JustFly1984

Also here is my "fix" (should have been this way to begin with):
```diff
-const messages = await import(`path/to/my/messages/${locale}.json`);
+const messages = (await import(`path/to/my/messages/${locale}.json`)).default;
```

**Comment by awwit** [comment] 2020-08-06 19:12
@jimisaacs 
I and @JustFly1984 are using TypeScript.

With your edits, we get this error:

`Property 'default' does not exist on type { ... } ts(2339)`

Because a json file is not a js module and does not have a `default` property (unless you specifically create it).

P.S. We do not use the `allowSyntheticDefaultImports` flag in `tsconfig.json` in our projects.

**Comment by jimisaacs** [comment] 2020-08-06 20:39
@awwit we are using `allowSyntheticDefaultImports` there's the difference.
