### ISSUE TITLE
react-intl in typescript not work

### ISSUE THREAD

**Issue by jhimelymendoza** [formatjs/formatjs#2174] opened 2020-10-02 00:50 UTC
Hi, I have the following problem, I have react-intl configured. but with typescript and everything works fine for me, but it throws me this error in console 
**TypeScript error in D: /Work/Study/briefcase/node_modules/react-intl/src/components/message.d.ts (2,13):
'=' expected. TS1005

    1 | import * as React from 'react';
  > 2 | import type {PrimitiveType, FormatXMLElementFn} from 'intl-messageformat';
      | ^
    3 | import {MessageDescriptor} from '@ formatjs / intl';
    4 | export interface Props <V extends Record <string, any> = Record <string, React.ReactNode >> extends MessageDescriptor {
    5 | values ​​?: V;**

**Comment by longlho** [comment] 2020-10-02 07:34
Dupe of #2128

**Closed as completed by longlho** 2020-10-02 07:34 UTC

**Comment by jhimelymendoza** [comment] 2020-10-02 15:40
Thanks, it had been like 4 hours on that
