### ISSUE TITLE
Starting `v5.18.0` the ICU `FormattedMessage` with `select` needs `other`

### ISSUE THREAD

**Issue by SudharakaP** [formatjs/formatjs#2987] opened 2021-06-18 13:25 UTC
## Which package?

`react-intl` package.

## Describe the bug

It seems that starting `react-intl` version v5.18.0 the `FormattedMessage` with a select argument needs to have `other` clauses. This breaks any `FormattedMessage` in existing code-bases. For example previous to this version,

```
<FormattedMessage
        id="AmountInterval"
        defaultMessage="{amount} {currencyCode} / {interval, select, month {mo.} year {yr.}}"
        values={{ amount: formattedAmount, interval: interval, currencyCode }}
      />
```
works well. But now this will break and we need to alter it as,

```
<FormattedMessage
        id="AmountInterval"
        defaultMessage="{amount} {currencyCode} / {interval, select, month {mo.} year {yr.} other{}}"
        values={{ amount: formattedAmount, interval: interval, currencyCode }}
      />
```

Some screenshots can be seen at this PR which we did to correct this issue; https://github.com/opencollective/opencollective-frontend/pull/6506

### Reproducible Steps/Repo

Easiest way to reproduce this is on our `opencollective-frontend` repo where we saw this issue. 

1. Clone https://github.com/opencollective/opencollective-frontend
2. Simply run `npm install` and `npm run dev` within the project folder to run the frontend repo.
3. Go to the page, http://localhost:3000/agora-collective and notice the broken `FormattedMessage` strings as shown on the screenshot in that PR. 

## Expected behavior

Either this break should be documented in the version upgrade notes or it shouldn't break when upgrading to the minor version. 🐨 

## Screenshots

![edit collective -- edit tiers (failed)](https://user-images.githubusercontent.com/806/122403861-ff3dc800-cf7e-11eb-92a2-52d6421a99e6.png)

**Comment by longlho** [comment] 2021-06-21 01:36
dupe of #2855 #2987

**Closed as completed by longlho** 2021-06-21 01:36 UTC
Labels: bug
